- name: Set Up
  hosts: local
  vars:
    - NODE_VERSION: "16"
    - FLUTTER_VERSION: "3.3.4"
    - NVIM_VERSION: "0.8.0"
    - LAZYGIT_VERSION: "0.35"
    - WINYANK_VERSION: "0.0.4"
  roles:
    - role: zsh
      tags:
        - zsh
    - {
        role: diodonfrost.p10k,
        p10k_prompt_style: "rainbow",
        zsh_plugin: ohmyzsh,
        p10k_transient_prompt: "yes",
        tags: p10k,
      }
    - role: tmux
      tags:
        - tmux
    - role: nvim
      tags:
        - nvim

    - role: nvm
      tags:
        - nvm
      nvm_profile: "/home/{{ user }}/.zshrc"
      nvm_version: "0.39.1"
      nvm_commands:
        - "nvm alias default {{ NODE_VERSION }}"
    - {
        role: geerlingguy.docker,
        docker_users: ["{{ user }}"],
        tags: docker,
        become: true,
        become_method: sudo,
      }
    - role: terraform
      tags:
        - terraform
    - role: christiangda.awscli
      tags:
        - aws
      become: true
      become_method: sudo
    - role: speedtest
      tags:
        - speedtest
    - role: flutter
      tags:
        - flutter
    - role: npm
      tags:
        - npm
    - role: misc
      tags:
        - misc
