- name: Set Up
  hosts: local
  become: yes
  become_method: sudo
  roles:
    - role: zsh
      tags:
        - zsh
    - {
        role: diodonfrost.p10k,
        p10k_prompt_style: "rainbow",
        zsh_plugin: ohmyzsh,
        p10k_transient_prompt: "yes",
        tags: p10k,
      }
    - role: tmux
      tags:
        - tmux
    - role: nvim
      tags:
        - nvim
    - role: geerlingguy.nodejs
      tags:
        - node
    - {
        role: geerlingguy.docker,
        docker_install_compose_plugin: true,
        tags: docker,
      }
    - role: docker
      tags:
        - docker
    - role: terraform
      tags:
        - terraform
    - role: christiangda.awscli
      tags:
        - aws
    - role: speedtest
      tags:
        - speedtest
