#!/usr/bin/env bash
set -e

tags="$1"

if [ -z $tags ]; then
  tags="all"
fi

if ! [ -x "$(command -v pip)" ]; then
  sudo apt install python3-pip -y
fi
if ! [ -x "$(command -v ansible)" ]; then
  python3 -m pip install --user ansible
fi

export PATH="$(eval echo ~$USER)/.local/bin:$PATH"
ansible
