#!/bin/bash -l
set -e

tags="$1"

if [ -z $tags ]; then
	tags="all"
fi

if ! [ -x "$(command -v conda)" ]; then
	bash scripts/miniconda-setup.sh
fi

ansible-galaxy install diodonfrost.p10k
ansible-galaxy install geerlingguy.docker
ansible-galaxy install christiangda.awscli
ansible-playbook -i ~/dotfiles/hosts ~/dotfiles/dotfiles.yml --ask-become-pass --tags $tags

if [ $tags = "nvim" ] || [ $tags = "all" ]; then
	nvim +PackerSync
fi
