#!/bin/bash -l
set -e

tags="$1"

if [ -z $tags ]; then
	tags="all"
fi

if ! [ -x "$(command -v conda)" ]; then
	bash scripts/miniconda-setup.sh
fi

if [ $tags = "p10k" ] || [ $tags = "all" ]; then
	ansible-galaxy install diodonfrost.p10k
fi

if [ $tags = "docker" ] || [ $tags = "all" ]; then
	ansible-galaxy install geerlingguy.docker
fi

if [ $tags = "aws" ] || [ $tags = "all" ]; then
	ansible-galaxy install christiangda.awscli
fi

ansible-playbook -i ~/dotfiles/hosts ~/dotfiles/dotfiles.yml --ask-become-pass --tags $tags

if [ $tags = "nvim" ] || [ $tags = "all" ]; then
	nvim +PackerSync
fi
