- name: Update and add dependencies
  ansible.builtin.shell: "sudo apt-get update && sudo apt-get install -y gnupg software-properties-common"

- name: Add gpg key
  ansible.builtin.shell: "wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg"

- name: Verifiy gpg key
  ansible.builtin.shell: "gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint"

- name: Add Hashicorp repo to apt
  ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

- name: Update Repository cache
  apt:
    update_cache: true
    cache_valid_time: 1
    force_apt_get: true

- name: Install Terraform
  apt:
    name: terraform
    state: latest
