- name: Install compose-swithc
  ansible.builtin.shell:
    cmd: "$ curl -fL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh | sh"

- name: Install tree cli
  ansible.builtin.apt:
    name: tree
    state: latest
  become: true
  become_method: sudo
